### ISSUE TITLE
Is there a plan for null-safety on yaml_edit?

### ISSUE THREAD

**Issue by asartalo** [google/dart-neats#102]
* Is there a plan? Would love to use it.
 * I can also help if someone can point me in the right direction. I started doing this on a fork on my own but I got stuck on `deepEqualsMap()` on `equality.dart` and didn't know how to deal with mismatching types. I'm fairly new to Dart and generic programming in general.

**Comment by LautaroLobo12** [comment]
+1

**Comment by jonasfj** [comment]
@asartalo we are definitely going to migrate it -- not sure quite when :D

But if you're interested in working on it, please do get started, feel free to file a WIP pull-request and ping me for feedback..

Otherwise, I'm sure we'll do it eventually as it's the same code we have in the `pub` client :D

**Comment by jonasfj** [comment]
Fixed and published as yaml_edit 2.0.0
