### ISSUE TITLE
unable to use server to serve a flutter web app

### ISSUE THREAD

**Issue by trailerzone** [google/dart-neats#133]
how would I go about serving my flutter app using shelf router? currently I am using it as my backend but when I put   app.mount('/app/', createStaticHandler('public/web')); it only shows a blank page, when i go to check the source the javascript information is in there, is shelf_router unable to serve up flutter applications? thanks

**Comment by jonasfj** [comment]
> when i go to check the source the javascript information is in there

I don't know how flutter apps are supposed to be hosted, is it supposed to be hosted at the domain root? maybe...?
But it sounds like `app.mount('/app/', createStaticHandler('public/web'));` is serving the static content from `public/web`, if that's not try please file a bug with a minimal example attached (possibly shared as a gist).

Maybe flutter apps need to run at the domain root, or you need to tell it what folder it's being served from... so that it can find its own resources -- I don't know.. Maybe look in the developer console for errors. Either way, if flutter applications can be served as static files, which I suspect they can, it's probably supported by `shelf_router`, but it might be that there is something the app build process that needs to know something else.
