### ISSUE TITLE
Route will download response if umlaut is in response

### ISSUE THREAD

**Issue by kiesman99** [google/dart-neats#37]
If you have an umlaut (ö,ä,ü) in your response, the response won't be displayed in the browser. Instead it'll be downloaded as a file.

```dart
import 'package:shelf/shelf.dart';
import 'package:shelf_router/shelf_router.dart';
import 'package:shelf/shelf_io.dart' as io;


class Api {

  Handler get handler {
    final router = Router();

    router.get('/without/<name>/<yas>', (Request req) {
      var name = params(req, 'name');
      var yas = params(req, 'yas');
      return Response.ok('I am a normal response $name $yas');
    });

    router.get('/with/<name>/<yas>', (Request req) {
      var name = params(req, 'name');
      var yas = params(req, 'yas');
      return Response.ok('I am a file ü $name $yas');
    });

    return router.handler;
  }
}

void main() async {
  final service = Api();
  final server = await io.serve(service.handler, 'localhost', 8080);
  print('Server running on localhost:${server.port}');
}
```

**Comment by jonasfj** [comment]
@kiesman99 can you check if this is a problem with `package:shelf_router` or `package:shelf`?

**Comment by jonasfj** [comment]
Please re-open if this is related to `package:shelf_router` :D

**Comment by yahu1031** [comment]
@kiesman99 and @jonasfj yes that might be the problem with `package:shelf` not sure cause the `Response.ok()` was from that package. So basically the response needs headers. If we haven't defined headers, that will think it was a file and the content of a file cannot be viewed directly in the web so it will download the file. If the response we expected was `text`, write the extension to the file downloaded and open it. It will show the content. If it is json data append the extension to the file and open it, you will able to see the content/response we need. So that, if we add headers to the response it will preview in that format.

**_This is your sample code data you expected right @kiesman99 ??_**

![image](https://user-images.githubusercontent.com/35523357/119240196-c53df980-bb6b-11eb-937a-36c3749ec0b2.png)

So here is another scenario (mine)

```dart

import 'package:shelf/shelf.dart';
import 'package:shelf_router/shelf_router.dart';
import 'package:shelf/shelf_io.dart' as io;

class Data{
  Handler get handler {
    final router = Router();
    router.get('/', (Request req) {
      return Response.ok(
        'Hello there 👋🏻',
        // Specifying header solved my emoji issues too.
        // Now I can even write up emojis 😎.
        headers: {'Content-Type': 'text/plain'},
      );
    });
    return router;
  }
}

void main() async {
  final service = Data();
    await io.serve(app, 'localhost', 1031).then(
      (value) => print('API running at http://localhost:${value.port} 🔥🔥🔥'));
}
```

**_My Output_**

![image](https://user-images.githubusercontent.com/35523357/119240334-7e9ccf00-bb6c-11eb-8e6c-d006c05adbf7.png)

Hope this clarified your issue. Please lemme know if not.
